DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS info;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE info (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    owner_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    playlist_title TEXT NOT NULL,
    html_df TEXT NOT NULL,
    FOREIGN KEY (owner_id) REFERENCES user (id)
)